---
- hosts: fs-ga
  tasks:
    - name: show interfaces packet load
      command: ifconfig -a
      register: interfaces
    - name:
      set_fact:
        packets: "{{ interfaces['stdout'] | regex_findall('RX packets:([0-9]+)') }}"

    - name: show results
      debug:
        msg: "{{ packets | map('int') | sum }}"